spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hiretrack_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # (use 'validate' or 'none' in production)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always  # Runs schema/data SQL files if present

server:
  port: 8082

springdoc:
  api-docs:
    path: /api/docs

security:
  jwt:
    secret: ${JWT_SECRET:VGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWxvY2FsLWRldi1qd3Qtc2lnbmluZw==}
    access-token-ttl: 15m

app:
  default-role: RECRUITER